### PR TITLE
fix: single cell selected when right-clicking a merged cell

### LINKED ISSUE #360: Right-clicking on a merged cell highlights wrong cell
**Describe the bug**
Wrong highlighted cell when right-clicking on merged cell.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by gazedreamily**
fix: single cell selected when right-clicking a merged cell
fix #360

### CODE REVIEW

File: packages/core/src/events/mouse.ts [hunk 1]
```diff
@@ -1402,10 +1402,6 @@ export function handleContextMenu(
   // }
   const workbookRect = workbookContainer.getBoundingClientRect();
 
-  if ((ctx.luckysheet_select_save?.length ?? 0) === 0) {
-    return;
-  }
```
Comment (zyc9012) [inline packages/core/src/events/mouse.ts:1407]: Why delete this?

Comment (gazedreamily) [reply packages/core/src/events/mouse.ts:1407]: We can change selection and open the contextMenu by right-click a cell out of selection now.
If we stay this, we can't use this feature when there is no selection.

**Review by zyc9012 — APPROVED** [review]
Thanks @gazedreamily LGTM
