### PR TITLE
fix: make scrollToHighlightCell generic

### LINKED ISSUE #391: Highlighted cell movement bug with frozen rows/columns
**Describe the bug**
If some rows and/or columns are frozen, then moving the highlighted cell using arrow keys causes the correct cell to be selected but the sheet view doesn't auto scroll.

**To Reproduce**
1. Open a sheet with frozen rows (say 2)
2. Scroll down a lot and select a cell in say row 30
3. Now press up arrow to move upwards

**Expected behavior**
The non-frozen view should scroll when the highlighted cell is beyond the viewing range.

**Screenshots**
image

Notice the disparity between cell selected and the sheet view.

### PR DESCRIPTION
**Pull request by sanchit3008**
Resolves #391

This pull request was necessitated due to Issue #391. The existing implementation of `scrollToHighlightCell` has two issues - 

1. It does not handle the cases where some rows or columns are frozen.
2. For scroll up/left, it has hardcoded values of 100 and 20 respectively which are not generic and won't suit the use cases where the cells above exceed these values.

To solve the first point, I am now checking if the sheet is frozen or not. If yes, then we set `freezeH` as the height of the total frozen rows, and `freezeW` as the width of the total frozen columns. In case there is no frozen in the context, we just set both of these to 0. When the scroll up/left conditions are triggered in lines 56 and 63, we simply check if `col_pre - scrollLeft - freezeW < 0` or `row_pre - scrollTop - freezeH < 0` are less than 0. Subtracting freeze allows us to prematurely scroll in case of frozen table, while not impacting non frozen tables at all.

To solve the second point, instead of scrolling by a fixed value of 20 or 100, I am making it scroll by maximum of the previously hardcoded value of 20/100 and the `freezeW`/`freezeH` parameter to make the scroll amount generic.

Edit - both hardcoded values were 20, I mistakenly took one of them as 100.

### CODE REVIEW

File: packages/core/src/modules/selection.ts [hunk 1]
```diff
@@ -33,21 +33,36 @@ export function scrollToHighlightCell(ctx: Context, r: number, c: number) {
...
+    const scrollAmount = Math.max(20, freezeW);
+    ctx.scrollLeft = col_pre - scrollAmount;
   }
 
   if (row - scrollTop - winH + 20 > 0) {
     ctx.scrollTop = row - winH + 20;
-  } else if (row_pre - scrollTop < 0) {
-    ctx.scrollTop = row_pre - 20;
+  } else if (row_pre - scrollTop - freezeH < 0) {
+    const scrollAmount = Math.max(100, freezeH);
```
Comment (zyc9012) [inline packages/core/src/modules/selection.ts:64]: The original amount is 20. Why do you change it to 100?

**Review by zyc9012 — COMMENTED** [review]
Thanks @sanchit3008 👍. The algorithm looks good. Just a question.

File: packages/core/src/modules/selection.ts (hunk 1 above)
Comment (sanchit3008) [reply packages/core/src/modules/selection.ts:64]: Sorry, this happened because before I implemented the maximum logic, I was experimenting with height = 100. This issue was solved with the Max logic but I forgot that the original value was 20 and not 100. I have updated this to 20, apologies for the confusion and thanks for spotting it.

**Comment by sanchit3008** [comment]
> Thanks @sanchit3008 👍. The algorithm looks good. Just a question.

@zyc9012 I have fixed the issue 谢谢

**Comment by sanchit3008** [comment]
@zyc9012 what is generally the release period after PRs are merged? I was looking to use this fix in my application.

**Comment by zyc9012** [comment]
@Qaplagzy Let's release a new version.

**Comment by Qaplagzy** [comment]
https://github.com/ruilisi/fortune-sheet/releases/tag/v0.18.0
@sanchit3008 @zyc9012
