### PR TITLE
fix: issue of initial formula inputs

### LINKED ISSUE #369: Clicking on cell values in formula editing - bug
If you enter an '=' into an empty cell, and then click on another cell that contains a value, the cursor moves to the left of the '='.

to recreate:
type 1 into cell A1
type 2 into cell A2
type = into cell A3 and then click on cell A1. 
The result is:   'A1='  instead of    '=A1'

### PR DESCRIPTION
**Pull request by shuanhukexuejia**
* fix #369  
* After entering '=' into an empty inactive cell, `ctx.formulaCache.rangeSetValueTo` gets wrong anchor element, need to check the first insertion and set `ctx.formulaCache.rangeSetValueTo` to null

### CODE REVIEW

**Review by zyc9012 — CHANGES_REQUESTED** [review]
The luckysheet impl uses `insertAfter`, not sure why it became `insertBefore` here

https://github.com/dream-num/Luckysheet/blob/99e6297e8f6e8c537e7ef140c34446f7239ba431/src/global/formula.js#L2742

So correcting it should do the fix, rather than patching `rangeSetValueTo`

https://github.com/ruilisi/fortune-sheet/blob/6c1be8a93eb54598cb02ba5b5a82fed4cca771d7/packages/core/src/modules/formula.ts#L3259-L3262

```js
    const eleToInsert = parseElement(function_str);
    if (ctx.formulaCache.rangeSetValueTo) {
      ctx.formulaCache.rangeSetValueTo.after(eleToInsert);
    } else {
      $editor.append(eleToInsert);
    }
```

**Comment by shuanhukexuejia** [comment]
@zyc9012 have fixed it, thanks

File: packages/core/src/modules/formula.ts [hunk 1]
```diff
@@ -3256,10 +3256,12 @@ export function rangeSetValue(
...
     const function_str = `<span class="fortune-formula-functionrange-cell" rangeindex="${functionHTMLIndex}" dir="auto" style="color:${colors[functionHTMLIndex]};">${range}</span>`;
-    $editor.insertBefore(
-      parseElement(function_str),
-      ctx.formulaCache.rangeSetValueTo
-    );
+    const eleToInsert = parseElement(function_str);
+    if (ctx.formulaCache.rangeSetValueTo) {
+      ctx.formulaCache.rangeSetValueTo.after(eleToInsert);
+    } else {
+      $editor.append(eleToInsert);
```
Comment (zyc9012) [inline packages/core/src/modules/formula.ts:3263]:
```suggestion
    const newEle = parseElement(function_str);
    const refEle = ctx.formulaCache.rangeSetValueTo;
    if (refEle && refEle.parentNode) {
      refEle.parentNode.insertBefore(newEle, refEle.nextSibling)
    } else {
      $editor.appendChild(newEle);
    }
```

**Review by zyc9012 — APPROVED** [review]
`after` and `append` are not supported in IE. Switched to compatible APIs.
