### PR TITLE
fix: error data with date format

### LINKED ISSUE #454: Valid date cell value (yyyy-MM-dd) is replaced by value "1900-01-00"
**Describe the bug**
When a cell formatted as "date" has valid date like "2023-04-01" (yyyy-MM-dd) is automatically transformed into "1900-01-00".

**To Reproduce**
1. Select a cell
2. Format the cell as "Date" type
3. Type a valid date that uses the format yyyy-MM-dd like for examle "2023-01-01"
4. Press enter

**Expected behavior**
The typed date correctly set.

**Screenshots**
wrong_date_format

### PR DESCRIPTION
**Pull request by gazedreamily**
fix #454

### CODE REVIEW

File: packages/core/src/modules/cell.ts [hunk 1]
```diff
@@ -284,6 +284,21 @@ export function setCellValue(
...
+          : vupdate;
+        cell.v = vupdate;
+        return;
+      }
+      if (mask?.[1].fa === cell.ct.fa) {
+        [cell.m, , cell.v] = mask;
+        return;
+      }
+      cell.m = vupdate;
+      cell.v = vupdate;
```
Comment (zyc9012) [inline packages/core/src/modules/cell.ts:301]:
```suggestion
    } else if (cell.ct != null && cell.ct.t === "d" && _.isString(vupdate)) {
      const mask = genarate(vupdate) as any;
      if (mask[1].t !== "d" || mask[1].fa === cell.ct.fa) {
        [cell.m, cell.ct, cell.v] = mask;
      } else {
        cell.v = mask[2];
        cell.m = update(cell.ct.fa!, cell.v);
      }
```

* `mask` is only null when the input is null, so just check if the input is string.
* If the input is not a valid date, update the `ct` and values
* If the input is a valid date, and the resulting `fa` is the same, just copy the values
* If the input is a valid date, but `fa` is different, re-format it

**Review by zyc9012 — CHANGES_REQUESTED** [review]
Thanks @gazedreamily.

**Review by zyc9012 — APPROVED** [review]
